openapi: 3.0.1
info:
  title: query database
  description: chat with your database
  version: 'v1'
servers:
  - url: https://rujswe14n3.us.aircode.run
paths:
  /api/meta:
    post:
      operationId: getDatabaseMeta
      summary: Get table names and fields in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatabaseRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseMeta'
  /api/query:
    post:
      operationId: executeSQL
      summary: Execute SQL query and return results
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
components:
  schemas:
    DatabaseRequest:
      type: object
      properties:
        uri:
          type: string
      required:
        - uri
    DatabaseMeta:
      type: object
      properties:
        dbs:
          type: array
          items:
            $ref: '#/components/schemas/Database'
    Database:
      type: object
      properties:
        name:
          type: string
        tables:
          type: array
          items:
            $ref: '#/components/schemas/Table'
    Table:
      type: object
      properties:
        name:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    Field:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
    QueryRequest:
      type: object
      properties:
        uri:
          type: string
        sql:
          type: string
      required:
        - uri
        - sql
    QueryResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
